#!/usr/bin/bash
version=`cat fas-openid.spec | grep "Version:" | sed 's/Version:[ ]*//'`
pybabel extract --mapping=babel.map --output=fas_openid/translations/en.pot --msgid-bugs-address="puiterwijk@fedoraproject.org" --copyright-holder="Patrick Uiterwijk" --project="FAS-OpenID" --version="$version" fas_openid/
