#!/usr/bin/bash
version=`cat fedoauth.spec | grep "Version:" | sed 's/Version:[ ]*//'`
pybabel extract --mapping=babel.map --output=fedoauth/translations/en.pot --msgid-bugs-address="puiterwijk@gmail.com" --copyright-holder="Patrick Uiterwijk" --project="FedOAuth" --version="$version" fedoauth/
